#! configuration/base.yaml
log_level: "zero2prod=trace,tower_http=trace,sqlx=trace"
application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
